sudo: required
services:
  - docker

before_install:
  - docker build -t testimage -f Dockerfile.dev .

script:
  - docker run -e CI=true testimage npm run test  

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-215163256042"
  bucket-path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY    